FROM vibioh/scratch

ENV ZONEINFO zoneinfo.zip
EXPOSE 1080

ENV API_PORT 1080

HEALTHCHECK --retries=5 CMD [ "/herodote", "-url", "http://localhost:1080/health" ]
ENTRYPOINT [ "/herodote" ]

ARG VERSION
ENV VERSION=${VERSION}

ARG TARGETOS
ARG TARGETARCH

COPY cacert.pem /etc/ssl/certs/ca-certificates.crt
COPY zoneinfo.zip /
COPY release/herodote_${TARGETOS}_${TARGETARCH} /herodote
