---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: herodote-api
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.27'
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m

  values:
    nameOverride: herodote-api

    image:
      repository: vibioh/herodote-api

    config:
      HERODOTE_LOGGER_JSON: "true"

    secrets:
      HERODOTE_DB_HOST: AgALW6V9uvjB8q3YcjYtzvqfbaJygUh+DIhwe8+ZMDzquQ+ZI5zAKrK1kDFMTmTx2RGmqAQ7OhmbIJwltO4eejaTp2IX4iAe/B4q8RCK/oJLw29zsYpCWD5kAy5BLeJ2wrLf3IsLOPoKF1T2QSxqZc85Wqw2B1w+sMfmPviEJcSWuiZ72MK5F1HDNhqGmDk1LvlTJNsBEI1mYFiTOajPusapr+J1OJUUgAuDjHs2l8/mHRrS/C3/OtchnAJULsOdagfCoHwUcdpkLLxj9lLUrYXFqADpHnX+z/rUcVQXLplMQW7HE29skO9RGnfjgJo7dBB+p5WHt/+4hyLt1fViOra7+Js7JamNbfpV6sZuhNFSMhUvfcRUNWtXUBdE14bZXelPq2HvJ+hVb3B0qo8Tf4UF0fNHAdYighaYqrTQk84P28bj/MDy34fyzLpoW7f3VE74w5im5T9nnrIrTIvKCjX459Ab0CSo12JCLlh3QZJ+RKMGtGJTIzyCbq8GTdiGCECoaboAiaL+NKfSUPDFtSumuaegKGFbSIOQNKcB8toNWjQnV/1YUhnKDjZ+5kG7whXN1q1f67egYujdeXWoNlYVZ/QCsTYUR7sfAMoGg/tC1ZXZu64DyI7KhqwtMOJYcjGKQB6skdQ0d175ngXmQlzIeV0J1gDXOX592SuYzfSC4Ny5nTaEnQ9lIyK3ZCh6jpGNJUgNX7dl6A3+dDFP8nHc90V1mXThcJUxCls=
      HERODOTE_DB_NAME: AgAURIwQ6tePZ7SGAJCeyagZoKmS7Er1rYMO3uujfGxhC5O0aPaZehujRSDswgxBDbWnzxh/IwQ6nmIA4u4jeX/HWo1ef5aJhxhZ+qgtr99SIe5YS3lK/RQ8DDLqbeBLVK0mxEqaAUKYWCFo8XxXNGz0is7uZCY1xvs+m7a6HCSuOyjpFmSgGX6mbTlQnv/UsiUUFooqDse8XtKMnQHQ7nvFsLTJjVHfwPsXeVWUKDkB6/5bTmoumn2JnGCVQU+MPoVfRslos+8tWO24Nv+mnm/Da1OrmOvjsIpB7/CIHr+IltTxTtNzVTwrmOGQWhZVDgYgEBbg+wIphUa6zeaJ4I0kxxvm5ecGMWI174coHHw0bOwfkQ8Y+w2P5cMBXKb6uYOQQ7GyGYrDDlG+cJ9KWT8b4LGGjeW3OtIDLUfJyM92iVGjYkKMVrlfvihxyBTGh0XGqhJbLjKOS9+e1Ll7wVtCYxeihjfGozOG1S9h8u4iXykQEXDE2d6G+Dn3USKZz2F4bRtZ848gOhaa++Xoakc3N2dJKSr3fRC4pe27XTuf8NxYy1TNSzpIYiSZfoCyPZseZUuhiueZR3gfMDdCSWWOAKnIOHCjO+q6XcJ8o5jFm7olH9ZnONCvBM4U0bhsCwite8NdBbDOyRt/BjbPKymLFmlxcVuEyLaPDSOqBsM4c3u2/6JNv2oKRsH8XiAp4v5fK25qkrUWcw==
      HERODOTE_DB_PASS: AgBU6uIj4UZ/QjLKc7HV9y4H+H1zqW3i+QEPwwmojDSJAr857ksDyZHLYM6a/rq2B8ML1DRr+WVOoYjvgLI6xzkek/QFXRraZJ6eGB2251/Mj9x9ER0V87RbMLGCpaSDC2XjQat9DTue7AbXatyvNiKzV9XKm+WW6vjR4NcNo9aHE7QLOetfqUAmGwzzoNmDktLfXo0hpNQXF/WtL04/J07xQVqmC5X7jyGqyTEAOQQvvAf2qzzR99bHTr6XpsFAen8oeU8ioxYBLOqh/+PeTMpicnxhmhk5pP2PXY2ebQIyd5sC31e1BDVmbQdlHOVdKT4z4k0vMa/Pzn3WwJXfyoFQveKWCKalw3tWaJMdIofWAWTmPbk46qNNtmuVozf+d8LHpO0ihq4ApzOA0rXgTPcfVpGu86COpN5vTyclSFIa5pZQMhapx4wBYA/y9MfOe1Lir+wbYKyLmAwwKxvCGWoshX7Zcm0sZ4CrV8ZtIZsC1stBAYn3AAlyfwdUf5r0l6K5Z/Uj03xIdz/SsZxISJeb8tc1jFSrJ1DxByjU9EvXlgCsHXg5vevav5E0/ZcUIIGqNsMxhL0V2KaYJCApvbpY213U54E29B+UT+ZXBOvTFnDbp4ihffLcWZrRpKfpfZ8aA+EX7yT8/SyS8DtQGEtwLSRSczt3rqxqMk8rXzLEILEW4cnCQB+fexUmfdZB0zIw13n7wbwXL6AkvYCvT+zdGwCWlW5eBguX9n9U7OC0vw==
      HERODOTE_DB_USER: AgCQ/x7DW5D1ZY8TK49x4Bvo1zW4hiEBkev5tHVXiYJVGtVHXNBukwpaI1yVRJswMotu6k+AYWltjWeXJAIZeYK0UhLlx8rKz0Cw8saRIQJysOeJ4TJhqVCB26wlxncf+QzK6omYh/UBEaP3Kid07J38aOkGjjKOkLUhQ1ZvBae2Ctpg+/Jukwl7KnTNLkrSSaoNspmbl+7GL5ejkYa7DB2uI9s89MfGeh4mEcsOZ+f1OPKkZ/m2ihVHW+vShSWs7CiHMMbLaYcL4XmXIi4Hca9XgTmK+FyKmTZT4bgLaeFrN27xnTE2MbMNg/X30tyqP8e21LCpxfYDepIk0evoc1QOLNvYiMoA7wjsjnIyzsZs1pEwbEcPZ5bfmaQGePTDT8kgcMrIYKW3seaUazWUBgpFI8csLNF5rIr6qUZQpQ30OZS7FjFtkftMhz2ILV3HKUEJ8Cnnz+LTtwAX5AWSLi298t25fNxxMZHj5zF0iUg/wkU49zWNcLL7m/Gz/ZwD64OcUJzWTJTHEuXWCj5DsHO5BrXt7FXKADBTs9m0knJsglTVutYlAYkL+kCd5/FSR7gJVvJD0iXriL3NSFZbLJfANDasjOMS3lHAtEmPAgY3qlFWX31FBW77IH/KqpBDLmAL3IFs4/WwnmDL5a5yrso3C6JO4kt5F4w5FEfS978mnsoBoiH3YRFbd50ZaTJnW/TA58YM0PGMQg==
      HERODOTE_HTTP_SECRET: AgAsab5r1kQIU7I4Lg8ncC07T+m9UVJCc+VCE0GJS+x48xsVc5thVKrHMXH68j4Uk03qhzHNai0pWxGTgbBOwxLTX7y4cPh4qzDQ8xfNHnvg/Ht7AWH51VyPIvEa7HevVtL66UgIXuqwSSIetHQTn58DbJCIiLBmxd/VvMdCWfi233FgE1dF8f2+16DN/OZ0I/Sfaf2StPhoIpmewB6YsQ+c5sDiW75TcIwtkxE9ENk6wT33bPl73dBwc3c4+y69vJC/hRAZHNloFXTLVA4MB32od5Dk2D/ZG+4WoFL5gegCWUhkmGvXUbC/18jQlqrxrn48otvdVJw1bDsTB121b7vXYB07xNhozdSijTanjuVzF2susAL0IchYQWpHQ8yFrzRX2Kn7EFymAVdoFRrnYDIKkBWHPV1in5kWWia6EtZHiWoFSTZKauLpCU59NI79fIDE5GcS47VQVhApJnxwQhkNpfqjf4UehKBl0Z3tZwSWW+TgDswNT2/oa07HobBx27IHxkz5HkrPuFtOPMQb7prz4DIKO7IQANN4DHcLi4u7M9T81sS4MllUdsVtoG1+j1rry1CnB91+X4Yg/j2c9I1osVSDXQCwUN/GlRDKTWN1nmWjQy8bKIU6n63W4FzwVV8ffVw085AbMfQffAUHJHgDxfPbTiydJQ3iUPRMxDtATFRnIfJN249Pp8gUh1aOf++1IldOdMml0FGO9iaFVpGsPLuCCL/OHR3GY+LEkQXuZkNt82jBmDOLXRCd9M2Vb7Nl1/DbWkdQ1M06NzQ=

    ingress:
      enabled: true
      hosts:
        - herodote-api.vibioh.fr

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: herodote-db
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: postgres
      version: '0.0.12'
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m

  values:
    nameOverride: herodote-db
    config:
      POSTGRES_USER: herodote
      POSTGRES_DB: herodote
    secrets:
      POSTGRES_PASSWORD: AgDNu66oPoh4UsOhaTFuZL8CXH9urhqCUTNKwmUsK9TS8PGY+WI0yhRIMcQ0zGeZnPALHsEv58HtBzhDHH5bbTcE6t0CxvFeWjLh788aBZBWtyCq5q9G0OlWQSIWJBluZuNHoNAQzWYFQ0hZFmEAuD1OgBRDXpeKVbuFgU0Wz8P4+ILF/Q3WyADF728wch4KJRAlk9A3ZS2jCE7U/5pwrvsn/6AIJ1Sbn9/BVz5vRQR73Gj5g2+dluPs1TokB/da7Sv1aO4w/bapB7dz4Ervhyyla5DuenqRxoftPKVDgI7rWUCzgGSbOpKb+XsJZ4eRQ9iDI4yMk8vNujJxxgQOlmWqzxm+oAKzdBAt5+uBMG7a7daHdZq2cnlR+hveSwVnfFo0z6LbGrONpmvX47NBP+ZmteKNBmU+IcNuUmIIip8vccPGH3ecBLfrvyk3pedOLMYUh3VzpX70CAnzCxEbXveD6fybWmqjvind3xtYQ7VEZvgBBOGGCwgLDNzfHpK6Q7zjJeNRXGcNdaB+C8vuF5beIR7RORrdjCn27kSS82BKyLhUoK+caEoBQLEpSKecQtyl63sV8wwdd/zZk/unk7V/vnfHMmWPuUpRuypdlXOkpqNm0WvVe6TgSMQfN5A6IVbJ/McarmkcnKsf6svMd3ONCA+X0iH2VQ9MxDFaQFUZaQL14rrM11sl9VRj2gAJRVbHg3SwjNicsyyfVrSOBE2t5nfi6LCiAo7QwjpFtjjtDYgigtA3EbXKeMjoFpL/UccTUwINJ/jsLxDssNs=
      FIBR_BACKUP_PASSWORD: AgCpMJUPrqpPRfWCG6ytb1Fp0Ts5MYCzLTv36xdStHMMxQ+kag6q8oIBkGqEdn/lIaa6+X0I/DNRsKIiWoGUgyDKSsigbfBV+Zd9YAei2zYyLjAH9nQPUuVjeWYJHUBWUA4JCYsQJdRF/GJw2+eULVK/VABj8Ng49tOzB6CnjMRX9z/qfbnI4HlYp41BSkvGkjWyXaiHbQvq0Z0K/LciWlyRJazA81h5qPbyNAF4OdtMWd7Id1wF92fizcFW/1+WJ7aAARNRMUIjghq0CHPsI6jWh8bU/RRvUVwtG3okJtAd2ZJMDP+Mv2wM7O8xpfiJVoTUW/nZ4QgiVpJkraJHk/I4HrGBBwm9LmpCHDeseBhVvlU6Wn8+jT0XWvshWLmOq134/b/t2kZ4jaE9rIev6JMl52TZ0y9S5rhnDdgwqu5mNEtxS8Fn0wZtWjMxuJvMl2y+wL1GNz3t8+ju5bTS2GreJV1UvPzfJkN1kx2RJCDFEBkUKU2mcuK/YSIkyDPhSCorGrKYCtT4NHyUAL4FWJDVEMOvaKECo+bKv18HPcGtCZy04uV2n7JsY+h9XEFqJJ70O1iRf1Jv7UwJm4T2LZCwWcqubE9o6DE/GFAz+abVWoEwWvBBFHB1fWR9fWiCyicfo13yDmCUVOaXqsZRN3Fdcjmc/kfjSqHY7w0cUpWyZUlfao1f7na15gSCmb6Wa6ZjmUj6GD6P4E+Dt6svVIrPSQtZslePeLLubpX2fmkiBmFaKXyQJnf67fn+xqml/rMvPIwSeV4rt3/yYX8=
