apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: herodote
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.53"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    skipCRDs: true
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: herodote
    image:
      name: vibioh/herodote
      tag: "202103132130" # {"$imagepolicy": "default:flux-herodote-web:tag"}
    config:
      HERODOTE_LOGGER_JSON: "true"
      HERODOTE_DB_HOST: herodote-db
      HERODOTE_DB_PORT: "80"
      HERODOTE_DB_NAME: herodote
      HERODOTE_DB_USER: herodote
    secrets:
      HERODOTE_DB_PASS: AgCl50IoVJ+bk1U7UP2rEFi15bQKHIxfTjiSvww2bFFrblpUiwlMLNvr066ogBkqI3KxwqrRzMlLxjA/YzLALzGjMym1MxzGDA3kn2dI2Il1xJOJqdYEsah/qioDJe/cyHJV895KLtOcimbC6xSHNXWsbIS7kU5DYOV6M1/l6g619kQJFsqNtsqB0z8a0msaWiBOwKBOjcj7wzB8kPCG9p5dcXFMJJBsagmEKH9WpmDaOLkpYwNVvr/ZvWEp/muyWLH+7ywBWvsWrTQmmVhyi/OAerljFNysUTwc4gtyUXTtQ0Aeo4hyb/OBuFY25xh89hdKRH86yayWmuZ/VGeBIXNxY7pWYsQDBPpPTdtOwjryy2UnY25BEh57gqlqK01AjrSWJzTL02kUmWbt0ppHF38JNEWnI/KeJr/XRtHZJbjx6EDX6e05e76lZkFFkPUgq8CNqgN5bmaFUJ+sCrMzv355yTkkszah0Y3JSHmQlRzyuFtq2fu2gDFVX7rl3Au70k9wB78LvW6XsvKWvWalWugyPZBqZWHDALLFzIkbIBscmgw1b2iLixo/ijFX85y8jstactP+QStUrgOmFmzFOhBRcgI0ogL+Jk4xmENd/PMFenSn8Fxbj2CS7/LzEMhSwzxx5e1IfcmonSpiQcqrXHu87K9JxZCoWnGEgbDSniC3tRcxGqDH1HlaNZrt5E5Eb1cYlOlZcd+//UMUIjc8Pd/JWrtOggwMCh8tMMA6G0zwMvnUVeHExhkyXYFJPYpc4/vaiuVIyv4JjJ9l9uc=
      HERODOTE_HTTP_SECRET: AgAsab5r1kQIU7I4Lg8ncC07T+m9UVJCc+VCE0GJS+x48xsVc5thVKrHMXH68j4Uk03qhzHNai0pWxGTgbBOwxLTX7y4cPh4qzDQ8xfNHnvg/Ht7AWH51VyPIvEa7HevVtL66UgIXuqwSSIetHQTn58DbJCIiLBmxd/VvMdCWfi233FgE1dF8f2+16DN/OZ0I/Sfaf2StPhoIpmewB6YsQ+c5sDiW75TcIwtkxE9ENk6wT33bPl73dBwc3c4+y69vJC/hRAZHNloFXTLVA4MB32od5Dk2D/ZG+4WoFL5gegCWUhkmGvXUbC/18jQlqrxrn48otvdVJw1bDsTB121b7vXYB07xNhozdSijTanjuVzF2susAL0IchYQWpHQ8yFrzRX2Kn7EFymAVdoFRrnYDIKkBWHPV1in5kWWia6EtZHiWoFSTZKauLpCU59NI79fIDE5GcS47VQVhApJnxwQhkNpfqjf4UehKBl0Z3tZwSWW+TgDswNT2/oa07HobBx27IHxkz5HkrPuFtOPMQb7prz4DIKO7IQANN4DHcLi4u7M9T81sS4MllUdsVtoG1+j1rry1CnB91+X4Yg/j2c9I1osVSDXQCwUN/GlRDKTWN1nmWjQy8bKIU6n63W4FzwVV8ffVw085AbMfQffAUHJHgDxfPbTiydJQ3iUPRMxDtATFRnIfJN249Pp8gUh1aOf++1IldOdMml0FGO9iaFVpGsPLuCCL/OHR3GY+LEkQXuZkNt82jBmDOLXRCd9M2Vb7Nl1/DbWkdQ1M06NzQ=
    ingress:
      enabled: true
      hosts:
      - herodote.vibioh.fr
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: herodote-db
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: postgres
      version: "0.0.19"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    skipCRDs: true
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: herodote-db
    config:
      POSTGRES_USER: herodote
      POSTGRES_DB: herodote
    secrets:
      POSTGRES_PASSWORD: AgDNu66oPoh4UsOhaTFuZL8CXH9urhqCUTNKwmUsK9TS8PGY+WI0yhRIMcQ0zGeZnPALHsEv58HtBzhDHH5bbTcE6t0CxvFeWjLh788aBZBWtyCq5q9G0OlWQSIWJBluZuNHoNAQzWYFQ0hZFmEAuD1OgBRDXpeKVbuFgU0Wz8P4+ILF/Q3WyADF728wch4KJRAlk9A3ZS2jCE7U/5pwrvsn/6AIJ1Sbn9/BVz5vRQR73Gj5g2+dluPs1TokB/da7Sv1aO4w/bapB7dz4Ervhyyla5DuenqRxoftPKVDgI7rWUCzgGSbOpKb+XsJZ4eRQ9iDI4yMk8vNujJxxgQOlmWqzxm+oAKzdBAt5+uBMG7a7daHdZq2cnlR+hveSwVnfFo0z6LbGrONpmvX47NBP+ZmteKNBmU+IcNuUmIIip8vccPGH3ecBLfrvyk3pedOLMYUh3VzpX70CAnzCxEbXveD6fybWmqjvind3xtYQ7VEZvgBBOGGCwgLDNzfHpK6Q7zjJeNRXGcNdaB+C8vuF5beIR7RORrdjCn27kSS82BKyLhUoK+caEoBQLEpSKecQtyl63sV8wwdd/zZk/unk7V/vnfHMmWPuUpRuypdlXOkpqNm0WvVe6TgSMQfN5A6IVbJ/McarmkcnKsf6svMd3ONCA+X0iH2VQ9MxDFaQFUZaQL14rrM11sl9VRj2gAJRVbHg3SwjNicsyyfVrSOBE2t5nfi6LCiAo7QwjpFtjjtDYgigtA3EbXKeMjoFpL/UccTUwINJ/jsLxDssNs=
      FIBR_BACKUP_PASSWORD: AgCpMJUPrqpPRfWCG6ytb1Fp0Ts5MYCzLTv36xdStHMMxQ+kag6q8oIBkGqEdn/lIaa6+X0I/DNRsKIiWoGUgyDKSsigbfBV+Zd9YAei2zYyLjAH9nQPUuVjeWYJHUBWUA4JCYsQJdRF/GJw2+eULVK/VABj8Ng49tOzB6CnjMRX9z/qfbnI4HlYp41BSkvGkjWyXaiHbQvq0Z0K/LciWlyRJazA81h5qPbyNAF4OdtMWd7Id1wF92fizcFW/1+WJ7aAARNRMUIjghq0CHPsI6jWh8bU/RRvUVwtG3okJtAd2ZJMDP+Mv2wM7O8xpfiJVoTUW/nZ4QgiVpJkraJHk/I4HrGBBwm9LmpCHDeseBhVvlU6Wn8+jT0XWvshWLmOq134/b/t2kZ4jaE9rIev6JMl52TZ0y9S5rhnDdgwqu5mNEtxS8Fn0wZtWjMxuJvMl2y+wL1GNz3t8+ju5bTS2GreJV1UvPzfJkN1kx2RJCDFEBkUKU2mcuK/YSIkyDPhSCorGrKYCtT4NHyUAL4FWJDVEMOvaKECo+bKv18HPcGtCZy04uV2n7JsY+h9XEFqJJ70O1iRf1Jv7UwJm4T2LZCwWcqubE9o6DE/GFAz+abVWoEwWvBBFHB1fWR9fWiCyicfo13yDmCUVOaXqsZRN3Fdcjmc/kfjSqHY7w0cUpWyZUlfao1f7na15gSCmb6Wa6ZjmUj6GD6P4E+Dt6svVIrPSQtZslePeLLubpX2fmkiBmFaKXyQJnf67fn+xqml/rMvPIwSeV4rt3/yYX8=
