apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: herodote-indexer
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: "0.0.25"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: herodote-indexer
    jobLabels:
      k8s-cleaner: "true"
    schedule: "0 6 * * *"
    image:
      name: vibioh/herodote
      tag: "202208141355" # {"$imagepolicy": "default:flux-herodote-web:tag"}
    config:
      INDEXER_DB_HOST: herodote-db
      INDEXER_DB_NAME: herodote
      INDEXER_DB_PORT: "80"
      INDEXER_DB_USER: herodote
      INDEXER_LOGGER_JSON: "true"
    secrets:
      INDEXER_DB_PASS: AgAmLWKCtgRKRPGyvZoJ2W4zZgbZBBo1a7pyTj3I+32lf3qFDRmX7tqJBY9BOPMJUwjJreU6sq92kP5vK21ZEZ9c9d8VBG/SmmksCQguVE7JItve/ea+EhNWHdjcQC9Ip2Y/qzCZ4bDkWts1IsSQHjxd6aYfcMRRSfbRpYm23P2AEFWD8WpDA9sI9D+HVxfuBIahCAkYGJ0k0mCSmDIFaMjVgKp8F5nFiA2AXNoF3DTQOB8QQHINAf+lRjBxWf5dCn21338m5Vtf+/hMTic4vLcgdoEHKMjYOFj9nKr4cCWAJNr3+SVcL/H9FJJ4flhjxOzyv4ZVlyErSWISRuJDjK6GyiHJkIoOLH8Xyrw1EiLlJVMnWvpvhXfOnGZ7y3PV9jJJoDgzxT+1hS6pNJyRsXXOsY1xae78VYrLWKFycUxRk6L1GQtJnblH1lICnaqg6XPs7URKElM2w4sPQtHjhatzjLilaqj1tfn2wncUcjaOTn+S1YSy6bWReYqjItRMF7BNddIuDUznnSo1zb8vpDBzp2Ljy+eQqhtQPLImvl1VqLqmJUPzWMX+WFJQsk3LLEfgwM4kL58sNJOmzcaVV/Vuk2GA61Ctjr0LJT2wZYkAqCpJL8561GOeD2OrwkS5c27eV5ZFK5DiNNazIkcIq4WaLbE2qzzd4e9nrnH4AkRxYDIKmaDWzwryacidBRCV864ShgZE1h3A7V2/0msmJxINOvpvY5xQTcYggecypePYBxGvoZ1bI5Z9ktf9BPVyy0vS2o5mSoS/j4ZUf4c=
    containers:
      - name: job
        command:
          - /indexer
