apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: herodote-indexer
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: "0.0.25"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: herodote-indexer
    jobLabels:
      k8s-cleaner: "true"
    schedule: "0 6 * * *"
    image:
      name: vibioh/herodote
      tag: "202207160753" # {"$imagepolicy": "default:flux-herodote-web:tag"}
    config:
      INDEXER_DB_HOST: herodote-db
      INDEXER_DB_NAME: herodote
      INDEXER_DB_PORT: "80"
      INDEXER_DB_USER: herodote
      INDEXER_LOGGER_JSON: "true"
    secrets:
      INDEXER_DB_PASS: AgBajr/GW4H96CEyEulzjOQKqSSaBTGbQFLIUiwrlocFu/mGuhPonx4cQ4mQBBMHoDOeAxnA9p7s0gfQWRBsw4ZkpVKvwt9FyHdSECurtCSN4UIPRgIvzpDb6qPUU7kI9WhhOqWOjcPbinpw24qP0+tyhTGPCBTUYnNwvXa1MxQ+Tu9MadLew66rLUlvDqU2wLtijG3AQ/rCQa3iF/MuAVeRBj98rS1v5EG/xYjN7GA0hEmpBx4MqCvUJQnJVMCrnl9pxRSOWXbXcFyoqwc7lPtRVi1+y8AkeftT81LoXoIsFaiLbvpp0fbt8yjSB5D2M+fKVYp5O9KOVJKZNRpiU2Kcm8q+aCFZe+02ygev6N+OK7mfzWH0OqA0R+u73mIMmVeSDDO2wbWGcWtDqfwQy8ZzjQw31+TEqaHZmd0sXatDko5S9Bq6HlxliSR2F1vpsmEowR4yRJ7RRy7dfNPEWBHKAJt52W/bijVdQ21ZlMibvap0hepwrosPW/pT+0FBrH1nC1oiAfqunb3vgN6xNkCKW4UwIMzrwgSFuS120qjWYPRp/Y8O5hHDYR3J3GpVGWJV0hO+HWuUWKhSZIDIOXZjuXdsU/Rdv+ZmRTs6ocBvNoY5ZVhwuDobxYhD5TbjeFWaCvfCpN/5/98i2tdfdqOJ1wuB+ZKS9pXYFrhcIeN08P4hCeKlUoB4phLtZvI/BqzMcUu5y1kSj7q8+VE22SxLkZKO2Mlp/d0yrg2hVnx+UuImxgDiaq0Utd0vCND5FmHDmgot8JaFHjl5ym8=
    containers:
      - name: job
        command:
          - /indexer
