apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: herodote-indexer
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: "0.0.22"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: herodote-indexer
    schedule: "0 6 * * *"
    image:
      name: vibioh/herodote
      tag: "202206171835" # {"$imagepolicy": "default:flux-herodote-web:tag"}
    config:
      INDEXER_DB_HOST: herodote-db
      INDEXER_DB_NAME: herodote
      INDEXER_DB_PORT: "80"
      INDEXER_DB_USER: herodote
      INDEXER_LOGGER_JSON: "true"
    secrets:
      INDEXER_DB_PASS: AgCEbkyOKj0t8BxZzXWKkC/QDUSyZ5f3XoVHBquuY+a+xRm2TO/3os4PIxss5JxBumWPnmIj/Illuex3PEBZA22iarY16cJ90NLFk1LVqxgPEWG0JJiGNJCySZkkEVkWwRJLtZU00jVlMDTkyAiAhvcuY9g9QkHawaP+4I9mvgJIAdokyXR+s1cQ+G0vlmlBWKbz0/vVWwS8yWMBv+GxKfQm4SpcFklHZp1MEkxBbJ5Muz44bUIeOOW4UikJ0drwhlk4i/0I8pSR9ulKagPe7rU+zB7fAI9oABv4SVYhF2xlM1UD6n1JMl9GqtS8/c4+/31YSDUt+dOj6EuzRNCuGioyEG8gbpgGqt/tCBAoNF6RJ1JGcJj+HVu3gHzvNYDO3O3AL/PGP+CiGtb+xSuIXs5CQvzkh/ORPdD5bPL/vSO2HOtiE+fzXr+4DVVwgJCPJ67V0LvedBgVwtSvt7eDDFOiTgNEM8A6iT2V2FMwTj2G9bSOezpr0cTzhmZmhut+qqaT0428p0yyOjLeIL0VGu+DFRmb+7PGAxTonRYmqr9zCtVmv8ecaJeNCZBVLwoVoEOV+RAEFlDVJ9xKT6b5pcf/doQ0tnorS/nPFa/bsjFZ0CcV5iV+kT1XHpKIrBoMaTo/PtBLIiKyOsqKlIZ3JJtzhM/QlgsGcfdRSWTk/AM4xcnuLZLZKJpAr+8UHbDKgnmjnClCxYscoNSTvVcZEstqC2TpTPsWayapGB/3Ga43W5mRnCHAXmLyP/btac+Wis9VqiYVZVOTiDHQ7HA=
    containers:
      - name: job
        command:
          - /indexer
