---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: herodote-db
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: postgres
      version: "0.0.30"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: herodote-db
    config:
      POSTGRES_USER: herodote
      POSTGRES_DB: herodote
    secrets:
      POSTGRES_PASSWORD: AgDNu66oPoh4UsOhaTFuZL8CXH9urhqCUTNKwmUsK9TS8PGY+WI0yhRIMcQ0zGeZnPALHsEv58HtBzhDHH5bbTcE6t0CxvFeWjLh788aBZBWtyCq5q9G0OlWQSIWJBluZuNHoNAQzWYFQ0hZFmEAuD1OgBRDXpeKVbuFgU0Wz8P4+ILF/Q3WyADF728wch4KJRAlk9A3ZS2jCE7U/5pwrvsn/6AIJ1Sbn9/BVz5vRQR73Gj5g2+dluPs1TokB/da7Sv1aO4w/bapB7dz4Ervhyyla5DuenqRxoftPKVDgI7rWUCzgGSbOpKb+XsJZ4eRQ9iDI4yMk8vNujJxxgQOlmWqzxm+oAKzdBAt5+uBMG7a7daHdZq2cnlR+hveSwVnfFo0z6LbGrONpmvX47NBP+ZmteKNBmU+IcNuUmIIip8vccPGH3ecBLfrvyk3pedOLMYUh3VzpX70CAnzCxEbXveD6fybWmqjvind3xtYQ7VEZvgBBOGGCwgLDNzfHpK6Q7zjJeNRXGcNdaB+C8vuF5beIR7RORrdjCn27kSS82BKyLhUoK+caEoBQLEpSKecQtyl63sV8wwdd/zZk/unk7V/vnfHMmWPuUpRuypdlXOkpqNm0WvVe6TgSMQfN5A6IVbJ/McarmkcnKsf6svMd3ONCA+X0iH2VQ9MxDFaQFUZaQL14rrM11sl9VRj2gAJRVbHg3SwjNicsyyfVrSOBE2t5nfi6LCiAo7QwjpFtjjtDYgigtA3EbXKeMjoFpL/UccTUwINJ/jsLxDssNs=
      FIBR_BACKUP_URL: AgDhtKpqqLE5r1lPmqjB1bpNR0BeLOTVXR5ZX+IwVkZD5cWJ3ty+B8Jmdn3m7LYwJhbhtMfgCPWt8QbZ09nAFiEMRsv7I6obADxlskRqpGXTigiFtuMqws0B021Kx5ct+qNhnMSv0Y/bHsGLlVc9lU6luMc9wG8whmNP1/C4U14zyHDFVaOBILLzUtfdC4CFXn/d0GGf1y1qbMVyxwucH/WJgzDn4oJdsHA3yJrfbnCpsc1NwhDo6DXdB3ACFtvbRuk7XWTpP1kPXUDlZ16cQsHTAyauzlZJqyQh3IftoAfkFZVND2CxUF0sXPnzmdxch8GwPDZ2nJ/ext0MBzJFo9+1R2oz8l40L37PyPU5p5HhmuV+vv7wD2NT8pYI2eumI3jNpXF/TNr9eBC+Lu895q+i6dB+d1u7eLU4Q0fLdQ623/8day03LgDsksKTkNqIiISTuKkqFQltpJ2CFS5Xx4zeV24HNx6tAvr8Pw5xvZ3A35mLG/KFW7LL/U7IS9q05yCUIGbcRS/px76UPbxlcFXLqHqNclWdphsAuxpabTCfkfqhVGjwHyNrKTfBbjhVfADndQIplTIUTyofT6t2w7vMZ3BlqM/OaENbHrXxprioFvyohqnefKhDz6lGXrAP80O7AVz7XrMvs3LOo9N7To5lS5hToBkZrKFZ3ucfAYSYNaOpdK6LTvUCPC9et6Bz4FE2vWdUrBtiJM6Y9KuYM87mDXGwx1J7/DjOTYPe34ikyCUn
      FIBR_BACKUP_PASSWORD: AgCpMJUPrqpPRfWCG6ytb1Fp0Ts5MYCzLTv36xdStHMMxQ+kag6q8oIBkGqEdn/lIaa6+X0I/DNRsKIiWoGUgyDKSsigbfBV+Zd9YAei2zYyLjAH9nQPUuVjeWYJHUBWUA4JCYsQJdRF/GJw2+eULVK/VABj8Ng49tOzB6CnjMRX9z/qfbnI4HlYp41BSkvGkjWyXaiHbQvq0Z0K/LciWlyRJazA81h5qPbyNAF4OdtMWd7Id1wF92fizcFW/1+WJ7aAARNRMUIjghq0CHPsI6jWh8bU/RRvUVwtG3okJtAd2ZJMDP+Mv2wM7O8xpfiJVoTUW/nZ4QgiVpJkraJHk/I4HrGBBwm9LmpCHDeseBhVvlU6Wn8+jT0XWvshWLmOq134/b/t2kZ4jaE9rIev6JMl52TZ0y9S5rhnDdgwqu5mNEtxS8Fn0wZtWjMxuJvMl2y+wL1GNz3t8+ju5bTS2GreJV1UvPzfJkN1kx2RJCDFEBkUKU2mcuK/YSIkyDPhSCorGrKYCtT4NHyUAL4FWJDVEMOvaKECo+bKv18HPcGtCZy04uV2n7JsY+h9XEFqJJ70O1iRf1Jv7UwJm4T2LZCwWcqubE9o6DE/GFAz+abVWoEwWvBBFHB1fWR9fWiCyicfo13yDmCUVOaXqsZRN3Fdcjmc/kfjSqHY7w0cUpWyZUlfao1f7na15gSCmb6Wa6ZjmUj6GD6P4E+Dt6svVIrPSQtZslePeLLubpX2fmkiBmFaKXyQJnf67fn+xqml/rMvPIwSeV4rt3/yYX8=
