---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: herodote-db
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: postgres
      version: "0.0.32"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: herodote-db
    config:
      POSTGRES_USER: herodote
      POSTGRES_DB: herodote
    secrets:
      FIBR_BACKUP_PASSWORD: AgDBeUAGOawP+tiUC+PH9wl0yVOIqHcwFMirtZ/HrBgq4GdHocFKxSlyKhJna3tyyrYaRxp3p4FtgH3ipJ6Wdxk0kEtAmYcFct8ZvKG8D6kJ9KSdDTVaW1m73rv2d3v70gmZD1fS8vdQYObcWlw8G5nAht9Ej2r4bmN/vAhAvsnIq/jUGZ2Sm7sy/RO0Ahf1ISWCDgSm/9RDjPtWDqs3rKJE2wWTQFwI1Q3uW2dCoSXpnKysw24zG/S6I+Lwc7WyRV4SrLCqfW59gxKDk5ey8wq2NY7kfxICMTol+m8Tr2HZq1ldWMTyzoeQz0LFFzNBNphPmYhs9yPAUhI9HUAp7JLRKIyvwGxVUeQCE8xFJOhfZPwPAuj4Z9iAs/HhYIYhWY0YN3GEOmmKqdsa4gAIzPib8z0IwX5BN0Xtdb/mwWTANMvAoCIVOzQbsiauDEb9sIPvoaPWrfrfPm9AyiMkQBLAEZWma4oxKBV9Nwi/aSDI0dnHUkiR90mzmm73SOl3f+082Ddk9Dp2o1Tyvu597My4dNjMJKGDxlp52AYPC+NpWRd8yOSy6PQM5JhUIll8wlRd9ZLMm6GTh1QACOzzkl5pcRpgRsXaXk+E0Sg5+902HTbnkAuJOKUgtcBsrmLrcdq4jaF2bybhW/QvhhDffg1HeRhkIsCfBGLq5joYxQ8XhJJlC4gitNSmRlb3EqjoZqljAAFURVYPrifzLRV3iqSELU/pJ8tdxCjUp15WQZuNWIt+xjDZSXzxx0DEhoE9cI4rYd+VsyeUmMhxVfE=
      FIBR_BACKUP_URL: AgBQiUlNzvSsBG+cmXM5qOVzsowuR3JbzrsGud8YxIVPVtmIYaepu/KfwnWM46niADFRRwCikKjoD2WCftEFwXXMYtoJvgFVZCGHvKYGIY5uEiaHg1g8jl2+M0OXGqdl9UZFqXcLK/ZZCFg2HjRYgbPzQvTMCcOZLZG81zuK+kRB9gDbM4IKyB+YpZomNcPHkFzU3QzBPPIVXQNcb1N9qDP79yhRDzo8mnlGoCF1AAmcmeP/1a2Is/gCD7nPnFxP3sw47aSIDl/vCDjUsNRnS/xO04T03fIdwwATljEXpK06E51taCBCQhgxAQFqNwf5diUpHlyHA8Jv+T8ouh/HLxC8Fi43gsJ+WwlRkmN84s8oXIOjzaa8NVpY0SJC7RGUHv7CXVt5EjyiDNM8leMl2mCDgXrD/lGVybWSIIqL6ISBh8Po22Mrp2gdRePiT5is+EP6kSeO8SiDLDFj8xR7Us3z4CcyRZvngSWINvta89iIbobKef/YKstLHiDFCRqsGUoh+RMBq3OMLPLAlb+jstFZtC65Eh9/XgBKUPRUwxR5u0mmDwJrbn8Sy9Z1EBK4TYtI1SzOtY3hxL48+KOZNWHL1jbf7F76xb0weO/86PyVwJqQtTXs8vGno8OnA3RwCFUyD6qQnm3M/BfoE4kRbkIJh2tD1HhoAKkecNMkV11msN9m5UEO2sWYnKv+r4DdcbBlfEq7V8P0bWCk6LGWwkrqdfF8FsEWnz4TVRCGQRdkuA==
      POSTGRES_PASSWORD: AgBuq4bpmuxIPlV6y1dQAKQWue9bhZ8lHpG/0I9823a7swiZG8Byj/D+VUOJS3Fz98CWuYwnHqLiRqkoASl6+Ei/4EgApwpceJMXLzo9rx/2fqvQV66FBXwuYtC8ShUgr3PZi6vj8H4SThc5hbjFx9QnJ3fVNw5xOire2Q4rB87ROln9oInnk5mIWsDhFA6du0sGfXaBLfWAr+UHzJRsAsEsNlcfPuVube23ykCxo/YOTJ+hfWywdd0H1QFJEw40eC9CIIDy5nT2qUY0XWyu2gwnI0DBMt1gH/EwKwSNr7Fti+AKSPL0GPFLcNk9UDYm44cO9YAjCYxafQCVD90JZ4hmmXZ0AgTiZeW4+FFIfUzbqNcP80wEJOhjqnvXJCeWwP20iaP1ws1n0OkFh3zn9WEdZNv4UP7S2NhmWkc2A5UnKPuI8BCakS7NQrtI9GppQVBr7OYGZzUuarS3E32EHqnFsCERyaPI+6uiO53yaMnOmUgZmS2XsB9vuvj4bDYjgO/GFD5odVeLTYnvTm0L+fGPtyqdaSuY8KYwQU1v2T2517dIlycvVQBTOilTJx/lKzxZ8bZIoKRaeV02X0ApQzukWiXj3rLlBq3FU2tywYycwHp+SVta84yRk9WEFlEZIkF3sssrW1UsJaWw7hI41HpgboBifBzBu1PleYMuTPcND25aINyaz7yA48Vf5NJPuU+6/mxGs1BrAu5xOqAiha7lPYruSxLnRE8Bl7+5/1a0r+Lht4aHkTYesK06cprHus1FCsXFbTHYEoA7Zn4=
