---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: herodote
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.30"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m

  values:
    nameOverride: herodote

    image:
      repository: vibioh/herodote-ui

    config:
      HERODOTE_API: https://herodote-api.vibioh.fr
      VIWS_LOGGER_JSON: "true"

    ingress:
      enabled: true
      hosts:
        - herodote.vibioh.fr
