apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: herodote
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.81"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: herodote
    image:
      name: vibioh/herodote
      tag: "202202191704" # {"$imagepolicy": "default:flux-herodote-web:tag"}
    config:
      HERODOTE_DB_HOST: herodote-db
      HERODOTE_DB_NAME: herodote
      HERODOTE_DB_PORT: "80"
      HERODOTE_DB_USER: herodote
      HERODOTE_LOGGER_JSON: "true"
      HERODOTE_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: herodote
    secrets:
      HERODOTE_DB_PASS: AgCMGQMqeqSl/6UKq4HWfg0P/tVaeV0pU95KFcinDfrEtYKPiixrxEY5Fk+CadOAQaONgbXm9d/f+M60FdUn+U8d0tneAR6F//9CBO+Yy6APM6Ang+rWVTDPzQNPz1GsmuxNTu+YBEknkb015XNsPZ8DYaJwV8yStxmiZbXbpcVXdK+iJUUnse0dgvZCSHAXU49OIhf+uLH97mOvhekjxLn0SIKrbfu3q2OkHZHly89eiwzOjw/2G0Hqvx0CPkYogCMtb9vpF08Dlh7f4C9saFkj7Zldg8ncoEeyEiU2THlgxGjAilGazOhClqxVdFZru3PibM6mwWk4MWe0Yx2O0YqzHLWVrTlG1atQ/KuTFhnpUUxnAxfaE8u+kjuLUfNDbtW2WxS2xA51IkR9sKuTuzoKwHSHYdvNmObOqVUmUPEhkP+yZcBukFmBvTceqN9/qU3PHSCkqy4jHw83Lp7Vd+Tr62rMMeP0QB0/u7wSrlRe2sd+Qs7HSYJ+G1EUg3ftyBNe3qkECdAwwkSMIdBFhIidG0qt5sFtRGhpFLAIanL7eOZ20Bg//ukOMP+C6nLluiYQCRrmyfGhIFIMaCg4s9D8CSYGtKQaxQ8UC2J/4hRakw0W0UnQpwOUrFVm8MmrfIG0QebNciuJimMS5kpsZeDDLDi/pnr22b245xxt8P05KBGrf+htFhTTf1V6eKpeIPLRbqhprRCLEvbHFQH+c93P0cBAMmXMRZ/TSWB+o+O1TVc3YvX5Wkuy64Sse8wdRS62BsektE4jTOuDfTM=
      HERODOTE_HTTP_SECRET: AgDMcZP8eNx9wKfHpbJxqpMtzquB43hQPrwCP0DAm5d4VLI8uQtkswn6n9nD5BY5OYHR0gufHhFD47T9/sw3Cjd9YuTjyLtM6oi1ExuenoQSJ+5E9cnRAinZserOIZe7nuh6wfr/xOvCjLicwvuPyeRAoIJojoALDqT4YZfERU8Eu9Ue+sOgNhbJCR05OPqU8TIPdTbkZmTEpp/huIJN/grxv6RgpO2/i0cqqTgNbJpP4Cc9a3ur2wYOUguh8hhvXoyeqoKc3KeKBNNqAsOtF1lk8KAg5bLhbX9+kwrz54PW+8WnbE7Qwv6/GRIa4Z6aXhvDXAYBug1doQwk7bO9rxSr1N+omeiuUM9duzciY0pOYampWvcwT3Jyzii4CsfPr0fbrK6rCqb3AlCWKGy+prk9hnVb/QqFw2eyKJwzyZyJv9t6HzKVXhsMx/YSz17wlrRc0au8HgXyFmSs8faluAI455sPkZxDzrD63tztr+Kiu+UiKShDqFUiMvESN/Rk17wY78y4fdQqxd4FDbuc7xHen9YdOw8HDcX9WMWomMDvM2mZODYo+CloiKkvdL8TtUUbP/0IlNxavmxoPHeF+xMzX5QYEAdpCKmoMGyi8I6nLsE83p90JbR49dCTREwfwFjS+cbBVcCZypZSSMTAmav2gNSKMMGZyhKm3yBVLtqRp+yW3T8KIDavlMiAQHUL9RGDAmgMhsC6l/k94iGErZaj/FiI4lmTgf3qM3QmVXGb6/RjYJNHQUr5zR0tXXRbikiJdSjI4dL0B+xT+qg=
    ingress:
      enabled: true
      compress: true
      hosts:
        - herodote.vibioh.fr
    canary:
      enabled: true
      url: https://herodote.vibioh.fr
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - herodote-db
              topologyKey: "kubernetes.io/hostname"
    pprof:
      enabled: true
