apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: herodote
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.85"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: herodote
    image:
      name: vibioh/herodote
      tag: "202207231118" # {"$imagepolicy": "default:flux-herodote-web:tag"}
    config:
      HERODOTE_DB_HOST: herodote-db
      HERODOTE_DB_NAME: herodote
      HERODOTE_DB_PORT: "80"
      HERODOTE_DB_USER: herodote
      HERODOTE_LOGGER_JSON: "true"
      HERODOTE_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: herodote
    secrets:
      HERODOTE_DB_PASS: AgCdorc3AdFTwd1Fs2YgLQIGJawTwpiMyrKea9IqSNaoOYaWt15uv9y9D3/OwK7TRtjtKm1z3OOPXqWYTrh7r2gQW7iQzXjJxeKRqsOC82TVuN1oDejIAkF7Tpsd0VRLrt6KXTKX/ez+FvLf/c9XCfJeazZPrETwI0FB+QcpJZeXCgOSQMNsyk1QFtQZ3uOn3DJodhQgRhmfNsETJN42yF+SU3H2ZfJptqYpX10ifTO26wdaNHgR1Lg4qI7zLJMA1TemGMHbhMUyDyzCsmtzmSs7ke4+Wk0hepGuQTm1Blg7bchSiIff/KcEejVddV9yUEehZeuMIIEmTYn5K4gEPm+k0+AnFT5Rlf/ifrcGMiUb7RvdZytP+llINMFLT06SgvRwwhiCr/3TvqeFXgTzzRUtE2YkGmpp5bHkjIdgn/zp9IinT8k9Yx/lefGYPBx/zHhGt4LKfijVUj+MPvGzHPrVX478eyy8VKRRaHH+EsIS1kkGDXGzMQY3jKDc9M2bEJZmhmqeeSP/IecB9B7mmEWC3QzMFqUXVb53Pq3xVXxQyvX26DS27jaFbPMK2XTD2h9h/71WEMG8tJxBViXfuMQQH9oUSd6f/x4CsGr0NCjM/I6JOm+y9JbsBSqRj/p1ove6DoXE651vlbmg0nU/AIz+sXB5b3gGiz/PvX/tiTHo0a3eDpqQRzGGtv5OQmqEal+Sigt81mty5qWlORsog2RbTLgDvtKaMRptOs9K7JE0FcSvhKn/8rmRbldSWWgyxxZ3JKQMHGobx8NflCY=
      HERODOTE_HTTP_SECRET: AgAgEZLj1eWb1durpolIigG+Ny1WrotFOQ3FpvZ7EnHQkr48xZvpXcOWCou18sj9tJutaOH4SpX3/NrSpxVowqv5L6GhNUawqa39hg625EU85e5MB+94u/GhjlrI+yemeS2W3ozo857pR9LcErDc7acjhvlodn7DMb7oOlp/hnAlPt/Oc6GnQ1Ohje7kreiub7A9Qey6sShXUnKxpTKsk1Kqu8hHuj1YETDsbzZ6P/p8GNbq/he1Cc6pfed1tc66SV1dRTl6WoYSN8n7JObPu5DlREVA8Sj0TTNcJEXrGLBVi2m8GpxOl8+CYl5TqOe5HCQmGdUGaDwYlenoB6pdcucaWKRuB0l1S3opquMfmX+bMB5eJT/P3Tm8t5bYPx1aRJane82+d1gU7hO3K4PmFpVMTnkux/yFFn8g5HjD90iJNCOPU0OWM8GaoMFgjiBWK8AsHtnaKrr7CNGgK1nK6tXFb/xYds/OXpKldMeH5BBxfe5brfg4wNJ6Hw5BlTsGXrbroXdahl2h30DGe+WCYy3xzZ/MEondZg10LDGfPYWMCVX8T2HRAN9yYO/++Qxv/nT0cu5o1kj+6jjZlKt72yFykZPt2IhYPi6P4zfWX/WVIa+SLD0nTsEBySE441VzXKw6aPhv6GW+pJqYJm7OelPumBsl9NtZTUTY/mDjaYrEIHxmZQIH9R3oxnnfJanTHBTWOXkugwEcP4njVKDn6VsgrrQmoWevAFcHAEC6WM6B0nSKgVg2q0UAbS8GBmnjKW+ajM3hbQdNyzT6UE8=
    ingress:
      enabled: true
      compress: true
      hosts:
        - herodote.vibioh.fr
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - herodote-db
              topologyKey: "kubernetes.io/hostname"
    pprof:
      enabled: true
