apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: herodote
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.82"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: herodote
    image:
      name: vibioh/herodote
      tag: "202207090744" # {"$imagepolicy": "default:flux-herodote-web:tag"}
    config:
      HERODOTE_DB_HOST: herodote-db
      HERODOTE_DB_NAME: herodote
      HERODOTE_DB_PORT: "80"
      HERODOTE_DB_USER: herodote
      HERODOTE_LOGGER_JSON: "true"
      HERODOTE_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: herodote
    secrets:
      HERODOTE_DB_PASS: AgCVZR1IsiBpklK/IrgvggZgFldpFSzzEQPQtSGzBRN7dNH0v0gzqYrephBsUrGOR2zQpv++lpaWUQJG1D5AdMctJAcnMG5iLRxLhet/Ii0z3VyFr10UEN8nS1QB6b5pGUPTPEV8aHTq2hAglimvbI8xsb0Fc9woqshH7WBApsr5tEUpZbRoei5Tqmh6soe25fKNXMnQES1bddOJGbi2/8cIVv19AN8V5U+KGI9wTq0lDKc/PbDHAaP0Qjq7Mkcf4fIqC/V27qBv0hWCwWYEkGzNNZAWztHxRg2oPBozQSxOFjRr+N9ugXUTYgTdpUTmtUSnRjSQPuOsXoa2T+chcJie15waQ/dMhtf7hHe+ua1xzs5WDwDh3xrgoQrTFsvNn7tq/PZDLyiy/k2I/n8X8s7c+UJdwjnz1TYfRnY6irP8PczHymw1CZx5egO2dELwJQF2i9V1/tYnKR4NElE4u++gCL7w158Fe00NIMvaOlHkQUQ7gIEi9BPErj6gqdSYdEKK0pfQ7zswK+mkFdWiLphviu5dyTsatJE1qHKt2imOpKXPWTnPQq36NUu0Qy/3glirfoSZVPuBMvoJ85A4s3vjxJS4XthpwMlazhW88LgF3DBtBR8/bKcG3B5y6ef9muLJXZYD0XunE5p7hxUgXj93wAjkfGRXgAPY5R05xIuKw/3E5zOOXjQntsKFvbNkoYIR9pI7O1TczLY8OgIP9sYYe5Lhll33VIFHh31eoMCFcR/3rPOvQl2QzzLuihn02FdvbEHDy2vKTe3xwVE=
      HERODOTE_HTTP_SECRET: AgBica5uC9nog/YYa1OWU65DgU6/TQ2SIBtJYrRsECbCLxLLLlN/TprzclpptXmrZa3gvacadTDuhDjJDy+XT6OeYOBCDnYV/fkpo2R5Vpa490opLCJShHksRAr/OWEoTVLV9hI8M2GXKlqoIezTLgda6VTOkDau4yxpagRndhmFUd4Q8JlvMUBAwgsWYyVXIHYhQDm6YpQq2Ng5Sxfl18qYCP92f6jCBZjgQ0XdK1Zw1ZMKA+dajYRoeMUh7DHdo+FTOJm/3CVRjKxPVkYI6VaqJMyh4G8qokgbJ02MSZ0EkhRTenZPXmDIeiUdFCwVnwSP9Jl1mIAWuOM1/yBKi44tknYHr4YTBOGI/e6ziPacriL5jiRAcQjCfhDLRnnsLoDwHFYh8SlDwvewD0hxoDI8LI5XXl3e0BJ4z5Ss8FeUxP6FcgT2Nu4Os/cO3oaH1cYYxgDU1eOwakivI2nJsgJ5ttppW8g5azhiZygiFZhvShtL8fq3PD1+kfL6U4XQGm6J86aKK58Oa32Bc7631c41sSbiYKc4NZ2WvzOZKnZ6LctfVuiwScJ63bzv/ah8IKetZSW+ClCUDnW0lrQtQsOxbOGH1zmdxSwpu7mdDV1sLfETYu87BZq+hmMq0A6cvgV4DkPAX2bIuhn1aWJb9R9cQdr5leJfn57Zxqu7JxVBSNOnDRHq++stjPUO8TTyTgy33AVWsLd1J8IqjXOfVwXNd41aNaOGUc+xu+2YRjTqS+RxncpjNz6EyA87RgFbsDBReaT6WDnD3lkYkJE=
    ingress:
      enabled: true
      compress: true
      hosts:
        - herodote.vibioh.fr
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - herodote-db
              topologyKey: "kubernetes.io/hostname"
    pprof:
      enabled: true
